FROM amazoncorretto:11
ENV GENERATION_DIRECTORY="c:\\packages"
ENV MAIL_ENABLED="Y"
ENV ERROR_SUBJECT_STRING="ERROR: RFM2 Package Generation"
ENV MAIL_SMTP_HOST="10.112.99.169"
ENV MAIL_SMTP_PORT="25"
ENV MAIL_FROM="RFM2PackageGeneration@mcd.comtest"
ENV DATASOURCE_0_URL="jdbc:oracle:thin:@aldb11ldbor01.rdisoftware.com:1521:rfm288"
ENV DATASOURCE_0_DRIVER="oracle.jdbc.driver.OracleDriver"
ENV DATASOURCE_0_NAME="oracle"
ENV DATASOURCE_0_USERNAME="rfm2us"
ENV DATASOURCE_0_PASSWORD="macqad"
ENV POOLDATA_CONNECTIONTIMEOUT="30000"
ENV POOLDATA_IDLETIMEOUT="600000"
ENV POOLDATA_MAXLIFETIME="1800000"
ENV POOLDATA_MINIDLE="1"
ENV POOLDATA_MAXIMUMPOOLSIZE="3"
ENV POOLDATA_AUTOCOMMIT="TRUE"
ENV USED_QUERY="oracle"
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]

